# Generated by Django 4.2.1 on 2023-05-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_place_latitude_alter_place_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='age_limit',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
