# Generated by Django 4.2.1 on 2023-06-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_adventure_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='description',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='description',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='image',
            field=models.ImageField(null=True, upload_to='booking/static/amenity_images'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='description',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='image',
            field=models.ImageField(upload_to='booking/static/itinerary_images'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.CharField(max_length=1024),
        ),
    ]
