# Generated by Django 4.2.1 on 2023-05-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_adventure_age_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='age_limit',
            field=models.IntegerField(default=0),
        ),
    ]
