# Generated by Django 4.2.1 on 2023-05-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_adventure_age_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='image',
            field=models.ImageField(null=True, upload_to='amenity_images'),
        ),
    ]
