# Generated by Django 4.2.1 on 2023-06-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_adventure_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='image',
            field=models.ImageField(null=True, upload_to='images/amenity_images'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='image',
            field=models.ImageField(upload_to='images/itinerary_images'),
        ),
    ]
